### PR TITLE
Verbose by default

### PR DESCRIPTION
**Pull request by Huluti**
Some users of [our forum](https://forum.manjaro.org/t/unstable-update-2017-01-12-xorg-1-19-gcc-pacman-mirrors/15554/26) would prefer that --verbose is the default comportment. What do you think guys? @Kirek @fhdk 
Here's what the PR changes:
- Verbose by default.
- Replace --verbose by --non-verbose. (no-verbose or non-verbose ?)

### CODE REVIEW

**Comment by Kirek** [comment]
If we do that, better change the arg to "--quiet"

**Comment by fhdk** [comment]
--quiet would resemple the action very well.

Change the⁣ default value of sekf.verbose to true. 

In command line parse reverse the assignment

Sendt af TypeApp ​

Den 14. jan. 2017 22.25, fra 22.25, Hugo Posnic <notifications@github.com> skrev:

**Comment by fhdk** [comment]
What is much more interesting is what error is thrown here?
[User screenshot in OP mentioned post](https://forum.manjaro.org/t/unstable-update-2017-01-12-xorg-1-19-gcc-pacman-mirrors/15554/24?u=fhdk)
AFAIK it should not be possible since a GTK_AVAILABLE variable is set at launch - which should prevent

**Comment by Huluti** [comment]
Fix in 5b20e18.
@fhdk can you open a new issue?

**Pull request closed without merging**
