### PR TITLE
Big review of all code

### PR DESCRIPTION
**Pull request by Huluti**
Here the news:
* New configs options:
  - Geolocation
  - MaxWaitTime
* Simplify big methods
* Several optimizations
* Better use of quotes
* Remove unuseful parts of code

Because it's a very big PR, I prefer to get reviews. Don't merge it now, we have to be sure that all works like before.
Thank's in advance!

### CODE REVIEW

**Comment by Kirek** [comment]
Good work, but there is a change I really don't like. 
Changing the format of the configuration file has consequences outside pacman-mirrors, because at least manjaro-tools, devtools and pamac read or write this file. It also doesn't deal with migration the old configuration file with the new and finally I don't see what's wrong with a classic ini style configuration file. So please revert that.

**Comment by Kirek** [comment]
https://github.com/manjaro/pacman-mirrors/pull/16/commits/3c37a3416224b9e255eeb45d197bfa2924243d3c is needes, as this file it's not called directly, but from https://github.com/manjaro/pacman-mirrors/blob/master/scripts/pacman-mirrors

"only_country" should be to custom after using interactive mode. It also should be removed when using "-c all"

**Comment by Huluti** [comment]
Didn't though about possible consequences.. just revert ini file. I'm doing the orthers needed changes. Thank's for your review.

**Comment by Huluti** [comment]
Why comment lines in conf instead of leaving blank values? This could be easier to read and set options. Does an other program depending of this file also use these comments?

**Comment by Kirek** [comment]
It's a common pattern on config files, putting the commented key with the default value

**Comment by Huluti** [comment]
Merged in #17.

**Pull request closed without merging**
