### PR TITLE
+ new mirror by @alpixtm

### PR DESCRIPTION
**Pull request by AlpixTM**
This mirror (https://mirror.alpix.eu) was added this morning
(https://github.com/manjaro/manjaro-web-repo/commit/95edb7ae943fb7595f86a4af42ea4b49f9af42f4).
I think, it must be added also here (correct me if im wrong)...
Added "{"country": "Germany", "url": "https://mirror.alpix.eu/", "protocols": ["http", "https"]},"
ignoring other changes @https://github.com/manjaro/manjaro-web-repo/commit/95edb7ae943fb7595f86a4af42ea4b49f9af42f4  because idk if those removed mirrors should be removed.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@Huluti and @fhdk: please double-check those changes. Thx.

**Comment by fhdk** [comment]
@AlpixTM @philmmanjaro 
It is only needed added at manjaro-web-repo.

Pacman-mirrors fetches the mirrorfile from that repo and what you see here is only workfiles they are not distributed with the package

**Comment by AlpixTM** [comment]
@fhdk Oh okay, my fault
Did this fact changed between Feb an now?
If i remembering crorrect, my other mirror was added (february) into a list in this package.

**Comment by fhdk** [comment]
Your memory serves you. You might be right.

With v4 no mirrorlist is in the package only a mirror file which is fetched from github a time of packaging.
The live media trigger pacman-mirrors to create the mirrorlist at runtime depending on location.

**Pull request closed without merging**
