### PR TITLE
Simplify UI

### PR DESCRIPTION
**Pull request by Huluti**
Following the remarks of @fhdk in #19, I made some changes.

- Remove the two different pages that were redundant by using dialogs.
- Uncheck servers by default.
- Add a cancel button.
- Improve the meaning of some sentences.

The GUI seems more user-friendly.

### CODE REVIEW

**Comment by fhdk** [comment]
Really nice - :

The change from `run` to `launch` - was it intended?

One weird thing though.
```
pacman -g -i -c Denmark,Germany
```
This gives a list of 10 mirrors.
Selecting only the top 4 mirrors
click Confirm and OK

```
cat /var/lib/pacman-mirrors/Custom
```
Gives 10 mirrors - the same with `/etc/pacman.d/mirrorlist`
Wouldn one expect the number of mirrors selected being reflected in the file?

**Comment by Huluti** [comment]
It is 'launch' and not 'run' because still the old code (PR is not merged ;))

Your problem is really strange, if I do what you describe my Custom file looks like this:
```
##
## Pacman Mirrorlist
##

[Germany]
Server = http://ftp.halifax.rwth-aachen.de/manjaro/$branch/$repo/$arch
[Germany]
Server = http://mirrors.cicku.me/manjaro/$branch/$repo/$arch
[Denmark]
Server = http://mirrors.dotsrc.org/manjaro/$branch/$repo/$arch
[Germany]
Server = http://mirror.netzspielplatz.de/manjaro/packages/$branch/$repo/$arch
```

**Comment by fhdk** [comment]
Yes - it is really weird.
```
[fh@geek-station pacman-mirrors-fhdk-branch]$ sudo pacman-mirrors -i -c Denmark,Germany:: Querying servers, this may take some time...
=> Mirrors in Denmark
=> Mirrors in Germany

:: User generated mirror list
--------------------------
:: Writing custom mirror file ...
:: Writing mirror list ...
:: Generated and saved '/etc/pacman.d/mirrorlist' mirrorlist.
:: Saved personalized list of mirrors in '/var/lib/pacman-mirrors/Custom'.
[fh@geek-station pacman-mirrors-fhdk-branch]$ cat /etc/pacman.d/mirrorlist
##
## Manjaro Linux repository mirrorlist
## Generated on 11 januar 2017 16:56
##
## Use pacman-mirrors to modify
##

## Country       : Denmark
## Response time :  0.003
## Last sync     : 0:04h
Server = http://www.uex.dk/repos/manjaro/stable/$repo/$arch

## Country       : Denmark
## Response time :  0.036
## Last sync     : 1:14h
Server = http://mirrors.dotsrc.org/manjaro/stable/$repo/$arch

## Country       : Germany
## Response time :  0.048
## Last sync     : 0:04h
Server = http://mirror.netzspielplatz.de/manjaro/packages/stable/$repo/$arch

## Country       : Germany
## Response time :  0.048
## Last sync     : 5:04h
Server = http://mirror.netcologne.de/manjaro/stable/$repo/$arch

## Country       : Germany
## Response time :  0.049
## Last sync     : 1:04h
Server = http://mirror.ragenetwork.de/manjaro/stable/$repo/$arch

## Country       : Germany
## Response time :  0.051
## Last sync     : 6:34h
Server = http://mirrors.cicku.me/manjaro/stable/$repo/$arch

## Country       : Germany
## Response time :  0.058
## Last sync     : 0:34h
Server = http://ftp.halifax.rwth-aachen.de/manjaro/stable/$repo/$arch

## Country       : Germany
## Response time :  0.068
## Last sync     : 11:14h
Server = http://ftp.tu-chemnitz.de/pub/linux/manjaro/stable/$repo/$arch

## Country       : Germany
## Response time :  0.078
## Last sync     : 0:14h
Server = http://repo.stdout.net/manjaro/stable/$repo/$arch

## Country       : Germany
## Response time :  0.152
## Last sync     : 6:54h
Server = http://repo.rhindon.net/manjaro/stable/$repo/$arch
```

**Comment by Huluti** [comment]
Have you tried with the current "pacman-mirrors.py" or the one of the newer PR?

**Comment by fhdk** [comment]
from the newer PR

**Comment by Huluti** [comment]
This means there is a regression in the new code ...

**Comment by fhdk** [comment]
I think I found it
```
        server_list = gui.server_list <------- should be gui.custom_list
        if not gui.is_done:
            return
        print("\n:: " + _("User generated mirror list"))
        print("--------------------------")
        # restore self.config["only_country"] to "Custom"
        self.config["only_country"] = ["Custom"]
        self.output_custom_mirror_file(server_list)
        self.output_mirror_list(server_list, write_file=True)
        # modify configuration to use custom
        self.modify_config() # function do self check
```

**Comment by Huluti** [comment]
Great job ;)

**Comment by fhdk** [comment]
Thank you for your help

**Pull request merged**
