### PR TITLE
translation review

### PR DESCRIPTION
**Pull request by fhdk**
I have created constants for the strings used and placed these in the top of the file

### CODE REVIEW

**Comment by fhdk** [comment]
we should remember to bump version

**Comment by Huluti** [comment]
Great work! You can even add the "Error:" string in a constant, to use it in errors messages.

**Comment by fhdk** [comment]
Trimmed even more strings to constants

**Comment by Huluti** [comment]
Very good work @fhdk! Thank you.

**Comment by fhdk** [comment]
@Huluti 
my pleasure - but thanks :)

**Pull request merged**
