### PR TITLE
Console UI

### PR DESCRIPTION
**Pull request by fhdk**
console ui
consoldated texts in separate file
pep8 recommendations fixed
ui classes renamed
generated pot-file
fixed tests

### CODE REVIEW

**Comment by Kirek** [comment]
Restore the empty __init__.py file in test and rename back the test_pacman_mirrors.py filename, I don't know why you are doing that...

**Comment by Kirek** [comment]
Looks great! Merging

**Comment by fhdk** [comment]
- sorry - 
I am learning 
the `__init__.py` has not been removed so I don't understand.
The recommendation of pulling the code through pep8 complained about 2 empty lines

The test file - I like readable output and the shortened name made my screen a lot easier to understand

The other things I implemented in the the test file is also beneficial for the understanding on what goes on but you can discard the if you don't like them.

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/issues/42

**Pull request merged**
