### PR TITLE
mirror-status

### PR DESCRIPTION
**Pull request by fhdk**
created a script for getting mirror status from repo.manjaro.org
parse repo.manjaro.org and create mirrorlist.json

the script is very basic for now but is this doable per long view?

### CODE REVIEW

**Comment by Huluti** [comment]
States of mirrors are already hosted on repo.manjaro.org. Why do you want to have a json file with these infos? Moreover, parsing the page ins't a durable approach and your code isn't linked to our existing code.
Sorry, but I can't merge this.

**Comment by fhdk** [comment]
The code in pacman_mirrors is querying every single server for their state file and parsing that file for the last time it synced. That process is inherently very slow. Parsing the content from repo.manjaro.org provides the status of the branches as well as the last time mirror synced.

And you're right it is not yet linked to current code but that was coming next.

And you asked me to look for 'strange' code but if you don't like it so be it.

**Comment by fhdk** [comment]
Close

**Comment by Kirek** [comment]
It would make more sense if the json file is provided by repo.manjaro.org
I believe the code is in https://github.com/manjaro/manjaro-web-repo/

**Comment by Huluti** [comment]
I think you had a good idea but like Kirek said the json file should be provided directly by repo.manjaro.com. Problem is that actually this code hasn't been touched for years.

**Comment by fhdk** [comment]
If the task is to optimize code and when I do it it us rejected and I can't get a clear indication of what is acceptable and what's not then I can't help you. 

I dont see the difference between a server-generated json file or a parse on code 'which hasn't been touched for years''. Then it probably won't change at all and why change it at all.

The proposed code takes only a few seconds to run. So why bother change it serverside?

-------- Original besked --------
Fra:Hugo Posnic <notifications@github.com>
Sendt:Thu, 05 Jan 2017 18:38:29 +0100
Til:manjaro/pacman-mirrors <pacman-mirrors@noreply.github.com>
Cc:"Frede H." <frede@hundewadt.dk>,State change <state_change@noreply.github.com>
Emne:Re: [manjaro/pacman-mirrors] mirror-status (#15)

**Comment by Huluti** [comment]
repo.manjaro.com has all infos about servers' states. It's easier to create a json file that could be hosted in repo.manjaro.com/state.json for example. No need to parse the page, just read this json file with python. Nothing presses, it is better now to think about a logical chain. 

Accepts reviews, we all want to help develop and everyone's opinions matter. You have succeeded in bringing a good idea. We only think that it can be implemented in a better way. Do not take this for rejection. We like to receive pull-request and chat around them.

Hope you understand.

**Comment by fhdk** [comment]
That ok by me.

I have made another PR on manjaro_mirrors.py

While refactoring manjaro_mirrors.py it became clear to me how to implement the mirror_status from the querying.

It will take a little more brainwork than has been done for now - but it is possible.

**Pull request closed without merging**
