### PR TITLE
bug-fixes and tested

### PR DESCRIPTION
**Pull request by fhdk**
replaces the previous PR
proof-reading  …
Test in terminal
pacman-mirrors -c Denmark -i OK
pacman-mirrors -c all -m random -i OK
pacman-mirrors -c all -m random -i -b stable OK
pacman-mirrors -g -c Denmark OK
Test on TTY
pacman-mirrors -g -c all -m random -i OK

Will you please review this PR? and thank you for your patience :)

### CODE REVIEW

**Comment by Huluti** [comment]
You deleted most of the commits I did previously ... why?

**Comment by philmmanjaro** [comment]
@Huluti: seems he didn't do a rebase on the changes you had made ...

**Comment by Huluti** [comment]
Oh.. you're right ;)

**Comment by philmmanjaro** [comment]
Maybe patch this pull to your local testbuild and reapply your made changes. How many got lost?

**Comment by Huluti** [comment]
10-12 commits

**Comment by fhdk** [comment]
On Sat, 2017-02-04 at 09:55 -0800, Hugo Posnic wrote:
> 10-12 commits

Do you think they exist in my fork?

Because I made a fresh fork of pacman-mirrors just before making the
PR.

**Comment by fhdk** [comment]
I am not aware I have done that. 

I had messed up my own fork and deleted it to start over. 

I have not made any changes to the manjaro repo but created a new
branch locally.

Also when pushing from VSCode I have made sure it was to my own repo.

So I am sorry if I unintentionaly have caused any trouble. Please
revoke that write access so it will not hapoen again.

Sendt af TypeApp
Den 4. feb. 2017, fra 18.13, Hugo Posnic <notifications@github.com>
skrev:

**Comment by fhdk** [comment]
I am not aware I have done that. 

I had messed up my own fork and deleted it to start over. 

I have not made any changes to the manjaro repo but created a new
branch locally.

Also when pushing from VSCode I have made sure it was to my own repo.

So I am sorry if I unintentionaly have caused any trouble. Please
revoke that write access so it will not hapoen again.

Sendt af TypeApp
Den 4. feb. 2017, fra 18.13, Hugo Posnic <notifications@github.com>
skrev:

**Comment by Kirek** [comment]
You first commit in the pull request reverts various commits done by Hugo.
For some reason the file where you made de changes where old instead of synced with the latest commit in the master branch. Maybe you had the file open when pulled the latest commits and your editor didn't reload the file.

**Comment by fhdk** [comment]
On Sat, 2017-02-04 at 22:16 -0800, Ramon Buldó wrote:
> You first commit in the pull request reverts various commits done by
> Hugo.
> For some reason the file where you made de changes where old instead
> of synced with the latest commit in the master branch. Maybe you had
> the file open when pulled the latest commits and your editor didn't
> reload the file.

I see - I think I know what I did.

If it is still the case I then please ditch my PR.

I know the small changes I made and will make a new PR based on your
master branch.

**Comment by Kirek** [comment]
Yes, better make a new PR.

**Pull request closed without merging**
